### ISSUE TITLE
generate_cookies() - encrypt() takes exactly 2 arguments

### ISSUE THREAD

**Issue by CameronSmith13** [sonya75/pooky-bypass#3]
While running the generate_cookies function I receive the error:

```
generate_cookies();
Traceback (most recent call last):

  File "<ipython-input-31-c3df80fc2c57>", line 1, in <module>
    generate_cookies();

  File "<ipython-input-30-ae932fa8376c>", line 69, in generate_cookies
    cookies["pooky_performance"]=encrypt(cookies["pooky"].replace("-","")[::-1].decode('hex'))

TypeError: encrypt() takes exactly 2 arguments (1 given)
```

because when running the encrypt function for the pooky_performance variable, the iv argument isn't defined

**Comment by HypePickups** [comment]
I don't even understand it, how and when do I run this script?

**Comment by sonya75** [comment]
The iv needed to input when the encrypt function is called would be the same as the other times its called. I will edit that. As for running it, those cookies need to added when you generate the old pooky cookies that were needed for supreme before. They added those new cookies before the bogo drop.

But anyway, the problem is that they keep changing the AES encryption key 5 mins before every drop. So you will need to figure out how to retrieve that. I wasn't planning on posting a script to automatically retrieve it.

**Comment by HypePickups** [comment]
do you know were exactly I would find this AES key on  their website?

(so basically from my understanding your script decryptes something in pooky then creates a cookie and decrypts it back and uses that to make supreme think your a manual user?

**Comment by sonya75** [comment]
As I mentioned earlier, I don't plan on posting the script to retrieve the key. If you want, you can try to figure it out yourself.

And the script just generates the cookies that the pooky javascript would normally create when browsing the website.

**Comment by zhongeric** [comment]
Sorry for digging up an old thread, but could you point us in the direction to find the AES key once its pushed by Supreme? I could try my hand at whipping up a script. Thanks! @sonya75

**Comment by pironside44** [comment]
I would also like to work together to figure this out. I've spent the last few days attempting to find the AES keys from the javascript files. I believe I'm close. If anyone wants to work together on this lmk. @sonya75 , @zhongeric

**Comment by zhongeric** [comment]
@pironside44 I'm definitely interested, shoot me an email at info@ericdomains.com.

**Comment by savannt** [comment]
Interested as well, shoot me an email if you'd like to discuss further. willits.supreme@gmail.com @zhongeric @pironside44 @sonya75
